// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATS3rNxF5foUqZ-kMxYPc6TJyfieokqPE',
    appId: '1:677288246627:web:9bd9cc161b1a8b30b22756',
    messagingSenderId: '677288246627',
    projectId: 'smart-cricket-scorer-21f7d',
    authDomain: 'smart-cricket-scorer-21f7d.firebaseapp.com',
    storageBucket: 'smart-cricket-scorer-21f7d.firebasestorage.app',
    measurementId: 'G-Z7BZXWJE7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpA9noNrmog7uiZoWrSZHTaYRGe8Kip0',
    appId: '1:677288246627:android:4ee27ea2be8e5a39b22756',
    messagingSenderId: '677288246627',
    projectId: 'smart-cricket-scorer-21f7d',
    storageBucket: 'smart-cricket-scorer-21f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0t-9PMAwrF-8Bmd0Mjs6LKw_LKx-V5E',
    appId: '1:677288246627:ios:252b9a21d11a6db3b22756',
    messagingSenderId: '677288246627',
    projectId: 'smart-cricket-scorer-21f7d',
    storageBucket: 'smart-cricket-scorer-21f7d.firebasestorage.app',
    iosBundleId: 'com.example.scoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0t-9PMAwrF-8Bmd0Mjs6LKw_LKx-V5E',
    appId: '1:677288246627:ios:252b9a21d11a6db3b22756',
    messagingSenderId: '677288246627',
    projectId: 'smart-cricket-scorer-21f7d',
    storageBucket: 'smart-cricket-scorer-21f7d.firebasestorage.app',
    iosBundleId: 'com.example.scoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATS3rNxF5foUqZ-kMxYPc6TJyfieokqPE',
    appId: '1:677288246627:web:7e0e3ea0212f3374b22756',
    messagingSenderId: '677288246627',
    projectId: 'smart-cricket-scorer-21f7d',
    authDomain: 'smart-cricket-scorer-21f7d.firebaseapp.com',
    storageBucket: 'smart-cricket-scorer-21f7d.firebasestorage.app',
    measurementId: 'G-CPLGRLWXNB',
  );
}
